Time of transactions
zeko-labs/zeko pull request #219
Opened 2024-10-14 16:03 UTC by MartinOndejka

Adds time to the diff on da layer. Needed for analytics and metadata for explorer.

Da nodes need to be upgraded first, then seqeuencer.

2024-10-16 16:05 UTC, L-as commented
Why does the DA need to know this? This smells wrong.

2024-10-17 12:01 UTC, MartinOndejka commented
> Why does the DA need to know this? This smells wrong.

It's our only persistent storage.

2024-10-17 17:12 UTC, L-as commented
I don't see how that means this is the correct solution.

What do you want to use the time information for?

2024-10-18 09:23 UTC, L-as commented on src/app/zeko/sequencer/lib/zeko_sequencer.ml
> +                  (Block_time.now (Block_time.Controller.basic ~logger))
move to da node as talked about

2024-10-18 09:23 UTC, L-as requested changes
DA node should not trust sequencer wrt. timestamp

2024-10-28 09:43 UTC, merged

2024-10-30 18:00 UTC, L-as commented
Please don't merge without re-review.